name: Conventional Commits

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate Commits
    runs-on: ubuntu-latest
    steps:
      - uses: taskmedia/action-conventional-commits@v1.1.18
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          types: "feat|fix|chore|revert"
          skip_merge: true
          skip_revert: true
